import type {
  Patient,
  SystemUser,
  QuickProtocol,
  InventoryItem,
} from './types';

// System Users with RBAC
export const seedUsers: SystemUser[] = [
  {
    id: 'USR-001',
    name: 'Dr. Karim Al-Baghdadi',
    role: 'doctor',
    department: 'Emergency Medicine',
    pin: '1234',
    permissions: {
      viewDashboard: true,
      viewPatients: true,
      editPatients: true,
      viewTriage: true,
      editTriage: true,
      viewClinical: true,
      editClinical: true,
      viewOrders: true,
      createOrders: true,
      viewLab: true,
      editLab: false,
      viewRadiology: true,
      editRadiology: false,
      viewPharmacy: true,
      dispensePharmacy: false,
      viewBilling: true,
      editBilling: false,
      viewAudit: false,
      viewInventory: true,
      editInventory: false,
    },
  },
  {
    id: 'USR-002',
    name: 'Nurse Fatima Hassan',
    role: 'nurse',
    department: 'Emergency Department',
    pin: '5678',
    permissions: {
      viewDashboard: true,
      viewPatients: true,
      editPatients: false,
      viewTriage: true,
      editTriage: true,
      viewClinical: true,
      editClinical: false,
      viewOrders: true,
      createOrders: false,
      viewLab: true,
      editLab: false,
      viewRadiology: true,
      editRadiology: false,
      viewPharmacy: true,
      dispensePharmacy: false,
      viewBilling: false,
      editBilling: false,
      viewAudit: false,
      viewInventory: false,
      editInventory: false,
    },
  },
  {
    id: 'USR-003',
    name: 'Pharmacist Ahmed Rashid',
    role: 'pharmacist',
    department: 'Pharmacy',
    pin: '9012',
    permissions: {
      viewDashboard: false,
      viewPatients: true,
      editPatients: false,
      viewTriage: false,
      editTriage: false,
      viewClinical: false,
      editClinical: false,
      viewOrders: true,
      createOrders: false,
      viewLab: false,
      editLab: false,
      viewRadiology: false,
      editRadiology: false,
      viewPharmacy: true,
      dispensePharmacy: true,
      viewBilling: false,
      editBilling: false,
      viewAudit: false,
      viewInventory: true,
      editInventory: true,
    },
  },
  {
    id: 'USR-004',
    name: 'Lab Tech Omar Ibrahim',
    role: 'lab-technician',
    department: 'Laboratory',
    pin: '3456',
    permissions: {
      viewDashboard: false,
      viewPatients: true,
      editPatients: false,
      viewTriage: false,
      editTriage: false,
      viewClinical: false,
      editClinical: false,
      viewOrders: true,
      createOrders: false,
      viewLab: true,
      editLab: true,
      viewRadiology: false,
      editRadiology: false,
      viewPharmacy: false,
      dispensePharmacy: false,
      viewBilling: false,
      editBilling: false,
      viewAudit: false,
      viewInventory: false,
      editInventory: false,
    },
  },
  {
    id: 'USR-005',
    name: 'Dr. Sara Al-Najjar',
    role: 'radiologist',
    department: 'Radiology',
    pin: '7890',
    permissions: {
      viewDashboard: false,
      viewPatients: true,
      editPatients: false,
      viewTriage: false,
      editTriage: false,
      viewClinical: true,
      editClinical: false,
      viewOrders: true,
      createOrders: false,
      viewLab: false,
      editLab: false,
      viewRadiology: true,
      editRadiology: true,
      viewPharmacy: false,
      dispensePharmacy: false,
      viewBilling: false,
      editBilling: false,
      viewAudit: false,
      viewInventory: false,
      editInventory: false,
    },
  },
  {
    id: 'USR-006',
    name: 'Receptionist Layla Mohammed',
    role: 'receptionist',
    department: 'Front Desk',
    pin: '2468',
    permissions: {
      viewDashboard: true,
      viewPatients: true,
      editPatients: true,
      viewTriage: true,
      editTriage: true,
      viewClinical: false,
      editClinical: false,
      viewOrders: false,
      createOrders: false,
      viewLab: false,
      editLab: false,
      viewRadiology: false,
      editRadiology: false,
      viewPharmacy: false,
      dispensePharmacy: false,
      viewBilling: true,
      editBilling: true,
      viewAudit: false,
      viewInventory: false,
      editInventory: false,
    },
  },
  {
    id: 'USR-007',
    name: 'Admin Hassan Ali',
    role: 'administrator',
    department: 'IT & Administration',
    pin: '0000',
    permissions: {
      viewDashboard: true,
      viewPatients: true,
      editPatients: true,
      viewTriage: true,
      editTriage: true,
      viewClinical: true,
      editClinical: true,
      viewOrders: true,
      createOrders: true,
      viewLab: true,
      editLab: true,
      viewRadiology: true,
      editRadiology: true,
      viewPharmacy: true,
      dispensePharmacy: true,
      viewBilling: true,
      editBilling: true,
      viewAudit: true,
      viewInventory: true,
      editInventory: true,
    },
  },
  {
    id: 'USR-008',
    name: 'Auditor Noor Khalid',
    role: 'auditor',
    department: 'Compliance & Audit',
    pin: '1357',
    permissions: {
      viewDashboard: true,
      viewPatients: true,
      editPatients: false,
      viewTriage: true,
      editTriage: false,
      viewClinical: true,
      editClinical: false,
      viewOrders: true,
      createOrders: false,
      viewLab: true,
      editLab: false,
      viewRadiology: true,
      editRadiology: false,
      viewPharmacy: true,
      dispensePharmacy: false,
      viewBilling: true,
      editBilling: false,
      viewAudit: true,
      viewInventory: true,
      editInventory: false,
    },
  },
];

// Quick Protocols (Pre-configured order sets)
export const seedProtocols: QuickProtocol[] = [
  {
    id: 'PROT-001',
    name: 'Malaria Protocol',
    description: 'Standard malaria workup and treatment',
    diagnosis: {
      code: 'B50.9',
      description: 'Plasmodium falciparum malaria, unspecified',
    },
    orders: [
      { type: 'lab', description: 'Malaria Blood Smear (Thick & Thin)' },
      { type: 'lab', description: 'Malaria Rapid Diagnostic Test (RDT)' },
      { type: 'lab', description: 'Complete Blood Count (CBC)' },
      { type: 'medication', description: 'Artemether/Lumefantrine (Coartem)', medicationId: 'MED-001', dosage: '80/480mg', frequency: 'Twice daily', duration: '3 days' },
      { type: 'medication', description: 'Paracetamol 500mg', medicationId: 'MED-010', dosage: '500mg', frequency: 'Every 6 hours PRN', duration: '3 days' },
    ],
  },
  {
    id: 'PROT-002',
    name: 'Pneumonia Protocol',
    description: 'Community-acquired pneumonia workup',
    diagnosis: {
      code: 'J18.9',
      description: 'Pneumonia, unspecified organism',
    },
    orders: [
      { type: 'imaging', description: 'Chest X-Ray (PA & Lateral)' },
      { type: 'lab', description: 'Complete Blood Count (CBC)' },
      { type: 'lab', description: 'C-Reactive Protein (CRP)' },
      { type: 'lab', description: 'Sputum Culture & Sensitivity' },
      { type: 'medication', description: 'Amoxicillin/Clavulanate 875/125mg', medicationId: 'MED-002', dosage: '875mg', frequency: 'Twice daily', duration: '7 days' },
    ],
  },
  {
    id: 'PROT-003',
    name: 'Acute Gastroenteritis',
    description: 'Dehydration and infection workup',
    diagnosis: {
      code: 'A09',
      description: 'Infectious gastroenteritis and colitis, unspecified',
    },
    orders: [
      { type: 'lab', description: 'Stool Culture & Parasites' },
      { type: 'lab', description: 'Electrolytes Panel' },
      { type: 'medication', description: 'Oral Rehydration Solution (ORS)', medicationId: 'MED-011', dosage: '1 liter', frequency: 'Every 4 hours', duration: '2 days' },
      { type: 'medication', description: 'Metronidazole 500mg', medicationId: 'MED-003', dosage: '500mg', frequency: 'Three times daily', duration: '5 days' },
    ],
  },
  {
    id: 'PROT-004',
    name: 'Chest Pain Workup',
    description: 'Rule out acute coronary syndrome',
    diagnosis: {
      code: 'R07.9',
      description: 'Chest pain, unspecified',
    },
    orders: [
      { type: 'lab', description: 'Troponin I (serial)' },
      { type: 'lab', description: 'Complete Blood Count (CBC)' },
      { type: 'lab', description: 'Lipid Profile' },
      { type: 'imaging', description: 'ECG (12-lead)' },
      { type: 'imaging', description: 'Chest X-Ray (PA)' },
    ],
  },
];

// Inventory Items
export const seedInventory: InventoryItem[] = [
  {
    id: 'MED-001',
    name: 'Artemether/Lumefantrine (Coartem)',
    category: 'medication',
    sku: 'ANTI-MAL-001',
    currentStock: 500,
    minimumStock: 100,
    unitCost: 5.5,
    isControlled: false,
    expiryDate: '2026-12-31',
  },
  {
    id: 'MED-002',
    name: 'Amoxicillin/Clavulanate 875/125mg',
    category: 'medication',
    sku: 'ANTI-BIO-002',
    currentStock: 800,
    minimumStock: 200,
    unitCost: 2.3,
    isControlled: false,
    expiryDate: '2027-06-30',
  },
  {
    id: 'MED-003',
    name: 'Metronidazole 500mg',
    category: 'medication',
    sku: 'ANTI-BIO-003',
    currentStock: 600,
    minimumStock: 150,
    unitCost: 1.8,
    isControlled: false,
    expiryDate: '2026-09-30',
  },
  {
    id: 'MED-004',
    name: 'Morphine Sulfate 10mg',
    category: 'medication',
    sku: 'OPIOID-001',
    currentStock: 200,
    minimumStock: 50,
    unitCost: 12.0,
    isControlled: true,
    expiryDate: '2027-03-31',
  },
  {
    id: 'MED-005',
    name: 'Tramadol 50mg',
    category: 'medication',
    sku: 'OPIOID-002',
    currentStock: 400,
    minimumStock: 100,
    unitCost: 3.5,
    isControlled: true,
    expiryDate: '2026-11-30',
  },
  {
    id: 'MED-006',
    name: 'Diazepam 5mg',
    category: 'medication',
    sku: 'BENZO-001',
    currentStock: 300,
    minimumStock: 75,
    unitCost: 2.1,
    isControlled: true,
    expiryDate: '2027-01-31',
  },
  {
    id: 'MED-007',
    name: 'Insulin Glargine (Lantus)',
    category: 'medication',
    sku: 'DIAB-001',
    currentStock: 150,
    minimumStock: 40,
    unitCost: 45.0,
    isControlled: false,
    expiryDate: '2026-08-31',
  },
  {
    id: 'MED-008',
    name: 'Amlodipine 5mg',
    category: 'medication',
    sku: 'CARDIO-001',
    currentStock: 1000,
    minimumStock: 250,
    unitCost: 0.5,
    isControlled: false,
    expiryDate: '2027-12-31',
  },
  {
    id: 'MED-009',
    name: 'Atorvastatin 20mg',
    category: 'medication',
    sku: 'CARDIO-002',
    currentStock: 900,
    minimumStock: 200,
    unitCost: 1.2,
    isControlled: false,
    expiryDate: '2027-10-31',
  },
  {
    id: 'MED-010',
    name: 'Paracetamol 500mg',
    category: 'medication',
    sku: 'ANALG-001',
    currentStock: 2000,
    minimumStock: 500,
    unitCost: 0.1,
    isControlled: false,
    expiryDate: '2028-12-31',
  },
  {
    id: 'MED-011',
    name: 'Oral Rehydration Solution (ORS)',
    category: 'medication',
    sku: 'FLUID-001',
    currentStock: 1500,
    minimumStock: 300,
    unitCost: 0.3,
    isControlled: false,
    expiryDate: '2027-06-30',
  },
  {
    id: 'SUP-001',
    name: 'Sterile Gloves (Size M)',
    category: 'supply',
    sku: 'PPE-001',
    currentStock: 5000,
    minimumStock: 1000,
    unitCost: 0.2,
    isControlled: false,
  },
  {
    id: 'SUP-002',
    name: 'Surgical Mask',
    category: 'supply',
    sku: 'PPE-002',
    currentStock: 10000,
    minimumStock: 2000,
    unitCost: 0.1,
    isControlled: false,
  },
  {
    id: 'SUP-003',
    name: 'IV Cannula 18G',
    category: 'supply',
    sku: 'IV-001',
    currentStock: 800,
    minimumStock: 200,
    unitCost: 0.5,
    isControlled: false,
  },
  {
    id: 'SUP-004',
    name: 'Syringes 5ml',
    category: 'supply',
    sku: 'SYR-001',
    currentStock: 3000,
    minimumStock: 500,
    unitCost: 0.15,
    isControlled: false,
  },
];

// Sample Patients
export const seedPatients: Patient[] = [
  {
    id: 'PAT-001',
    name: 'Mohammed Ahmed Hassan',
    dateOfBirth: '1985-03-15',
    gender: 'M',
    nationalId: '198503151234567',
    phone: '+964 770 123 4567',
    address: 'Al-Karrada District, Baghdad',
    identityLevel: 'L2',
    biometricVerified: true,
    registeredAt: '2026-02-28T08:30:00Z',
    registeredBy: 'USR-006',
  },
  {
    id: 'PAT-002',
    name: 'Fatima Ali Hussein',
    dateOfBirth: '1992-07-22',
    gender: 'F',
    nationalId: '199207221234568',
    phone: '+964 780 234 5678',
    address: 'Al-Mansour, Baghdad',
    identityLevel: 'L2',
    biometricVerified: true,
    registeredAt: '2026-03-01T09:15:00Z',
    registeredBy: 'USR-006',
  },
  {
    id: 'PAT-003',
    name: 'Omar Khalid Ibrahim',
    dateOfBirth: '2010-11-08',
    gender: 'M',
    phone: '+964 790 345 6789',
    address: 'Al-Jadriya, Baghdad',
    identityLevel: 'L0',
    biometricVerified: false,
    registeredAt: '2026-03-03T14:45:00Z',
    registeredBy: 'USR-006',
  },
  {
    id: 'PAT-004',
    name: 'Layla Hassan Mohammed',
    dateOfBirth: '1978-05-30',
    gender: 'F',
    nationalId: '197805301234569',
    phone: '+964 750 456 7890',
    address: 'Al-Adhamiya, Baghdad',
    identityLevel: 'L2',
    biometricVerified: true,
    registeredAt: '2026-03-04T07:20:00Z',
    registeredBy: 'USR-006',
  },
  {
    id: 'PAT-005',
    name: 'Ahmed Rashid Nouri',
    dateOfBirth: '1955-12-12',
    gender: 'M',
    nationalId: '195512121234570',
    phone: '+964 760 567 8901',
    address: 'Al-Kadhimiya, Baghdad',
    identityLevel: 'L0',
    biometricVerified: false,
    registeredAt: '2026-03-04T11:00:00Z',
    registeredBy: 'USR-006',
  },
];
